### ISSUE TITLE
integrate the endpoint already implemented for sign in with the front end

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#106]

**Comment by Janiel777** [comment]
With the user table already created in the database and the end point with which the front will communicate already implemented, now we only have to integrate these functions to conclude that the user can register on the page. Additionally, it is necessary to create a way to verify the email so it will be necessary to implement new code, new endpoints and use new dependencies to implement all this. So it is a task that involves understanding someone else's code, creating new code, integrating all these changes and improvising along the way exploring the best ways to implement this. So because of this I understand it is reasonable to give a total of 20 points to this task.

**Comment by irsaris** [comment]
Looks like a nice idea, could you suggest the scoring?

**Comment by Janiel777** [comment]
I think Difficulty: 5 and Priority: 4 for a total of 20 points.
