### ISSUE TITLE
Implement "Next" Button for Additional Information Page

### ISSUE THREAD

**Issue by BreannaGSegarra** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#184]
Implement the next button for the additional information page, which has the following specifications:
1. Display "Next" button whenever user is done adding an entry to the additional information section.
2. Have "Next" button take user to the preview page.

Recommended Priority: 3
Recommended Difficulty: 4

**Comment by Mark-Anton** [comment]
The next button UI design:
![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/42784582/32a8c29d-60bc-43c1-8990-e2d214f62a05)

*Before the next button could function, the user must save information in the prompt, otherwise the next button will close the prompt without saving the user's input.
![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/42784582/f7a9c5c7-50d8-494d-9eb2-2cc0658b18e9)

Once there is saved information, the next button will take the user to the next available Modal that requires input. 
If no Modal requires input it will close the prompt.
![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/42784582/31343bca-e325-4381-ace6-4b6dbcf7d743)

**Comment by irsaris** [comment]
Hello, where is the PR for this?

**Comment by Mark-Anton** [comment]
Next Button for Additional Information page #205
