### ISSUE TITLE
[Lecture Topic Task] QA stakeholders and add Domain Rough Sketch to Documentation based on QA (2.1.1) 

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#6]
The 'rough domain sketch' would include the specifics that you were told. The domain rough sketch refers to an application: the domain is that part of the observable universe that is of interest to your project, but independent of a system-to-be. Rough sketches are for collecting unprocessed information for example from brainstorming sessions, interviews, literature review, …

QA with potential users of the site to gather information to write the rough sketch. Not asking what they would think about it but their experiences in doing actions related to the domain, not the application. Then focus on what feature you can gather and write them down in the documentation.

**Comment by PinkSylvie** [comment]
@Negroni1 @irsaris @BreannaGSegarra Hello! I finished the rough sketch and got it looked over by the professor he said it looked good. If you'd like to take a look at it, I'm linking to the milestone document [here!](https://docs.google.com/document/d/1StfmPGMAUl4LZwA9w4PqyI1FdQ5Lno4EMKGMrhizV6Y/edit). I highlighted it as well since the prof said last semester that new changes to the document needed to be highlighted diffrently to see what was changed or added each milestone.

I'll also be linking the questionaire I used to interview the three stakeholders, only one of them answered it reason why I didn't include their answers. For the other two it turned out more fruitful to have a conversation about their resumes instead of going with the questionaire. [Questionaire](https://docs.google.com/document/d/11lV_Akt3fswBz_oh-jfzvrvDWv-2QOnnQ9T3SQNa-U4/edit)

**Comment by irsaris** [comment]
@PinkSylvie Hi, I would say that it's fine by me. Appreciate you going the extra mile to also have the professor look over it. 
On the highlighting matter, that's only applicable from the second milestone onwards so it's not necessary right now. I also think it's a good idea to link the Questionnaire document in the section. Good work!
