### ISSUE TITLE
Implement User Component

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#8]
This task involves the creation and implementation of the basic User Object which will contain he information of that a user gives when an account is created in the sign up page. This component is expected to ebe expanded upon and utilized across the different pages. 

To complete: Initialize the basic User Object in th repository, give it its basic attributes according to the schema created and make getter and setter functions for the component.

Score: Tentative ATM

**Comment by Janiel777** [comment]
@Negroni1  @PinkSylvie @irsaris 

I would like to give some comments on this issue as there are a few things I would like to raise for discussion.

Because the words “object” and “getters and setters” are mentioned, I understand that in the description of this issue, I think it may be referring to creating a JavaScript class that has as attributes the information that defines a user along with their getters and setters methods. It causes a bit of confusion since at the same time it uses the word Component, which can imply that what is being worked on in this issue is a react component. However, a pure JavaScript class and a react component are not the same.

The main reason why it is not recommended to use a JavaScript class to handle state in React is because React does not automatically detect changes to the properties or states of pure JavaScript classes. When the attributes of a class change due to a setter, React has no built-in mechanism to know that those changes occurred and therefore will not automatically re-render the affected components. Instead, hooks like useState or useContext provide a built-in trigger way to handle state that React can track and respond to changes, ensuring the UI updates appropriately.

Having stated my reasons why I believe it is not necessary to create a JavaScript class to handle user input, I am open to discussing other opinions.

If it is not necessary to create a JavaScript class to handle user information, I would like to propose a new proposal for this issue.

Title: using useContext (a react hook), make user information accessible from any component.

Description: One way to do this is by passing user information through props. The problems this can bring is that if we want user information to be accessible from any component, with props, you need to manually pass information from one component to another through each level of the component tree, which can be difficult. to maintain for data that must be accessible globally or by many components. This is why I propose to use useContext. UseContext allows components to access data directly from the context they are in, eliminating the need for prop drilling (passing props through many levels) and making it easier to manage global state and reuse components.

How would this task be performed:

1. Create a User Context: First, you will need to create a new file for the context, for example, UserContext.js. In this file, the context and a provider for it will be created. Keep in mind that here in this same file you can define what a user is in the following way when using the useState hook:
```javascript
const [user, setUser] = useState({
     id: "1",
     name: "Janiel",
    //so on adding all the properties you want
   });
```
To maintain project organization, you can create a folder called contexts at the same level as components.

2. Wrap the Application with the UserProvider: The App.js file would be modified to include the UserProvider around the components. This will allow access to the user's context anywhere in the application.

3. Access and Modify User State in Components: Now that the application is wrapped in the UserProvider, the useUser hook could be used to access or modify the user state in any component.

4. Show results: make a provisional message with some label or UI material component such that the user's information can actually be accessed from any component.
